# 고급대기과학 실습 2 (2022.03.12 @Yeji Choi)
## 2. basic_numpy 

In [2]:
import numpy as np

In [3]:
data = [0, 1, 2, 3, 4, 5]

In [5]:
arr = np.array(data)
arr, type(arr)

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [6]:
arr * 2

array([ 0,  2,  4,  6,  8, 10])

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0])

In [8]:
data.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [9]:
arr.dtype

dtype('int64')

In [10]:
len(arr)

6

In [11]:
arr.shape

(6,)

In [13]:
arr_new=np.array([[1,2],[3,4]])
arr_new.shape

(2, 2)

In [14]:
print(arr.ndim)
print(arr_new.ndim)

1
2


In [15]:
arr_new * 2

array([[2, 4],
       [6, 8]])

In [16]:
arr_new - arr_new

array([[0, 0],
       [0, 0]])

In [17]:
arr_new = arr_new.astype('float32')
arr_new

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [19]:
arr_new = arr_new.reshape(4)
arr_new

array([1., 2., 3., 4.], dtype=float32)

In [20]:
arr_new = arr_new.reshape(2,2)
arr_new

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [88]:
arr_new = arr_new.reshape(1,4)
arr_new

array([[1., 2., 3., 4.]], dtype=float32)

In [89]:
print(arr_new)
arr_new=arr_new.flatten()
arr_new

[[1. 2. 3. 4.]]


array([1., 2., 3., 4.], dtype=float32)

## __색인 시스템__
- 0..8까지 9개의 순차적인 정수를 원소로 하는 3x3 형상의 행렬을 구성해 봅시다.

In [52]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
arr[0,0], arr[1,2]

(0, 5)

In [26]:
arr[-1]

array([6, 7, 8])

In [27]:
arr[:,0]

array([0, 3, 6])

In [28]:
arr = arr.reshape(3*3)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
nums = list(arr)

In [30]:
nums

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [31]:
nums[:2]

[0, 1]

In [32]:
nums[2:]

[2, 3, 4, 5, 6, 7, 8]

In [33]:
arr[:2]

array([0, 1])

In [34]:
arr[2:]

array([2, 3, 4, 5, 6, 7, 8])

In [35]:
arr = arr.reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
arr[:, 0]

array([0, 3, 6])

In [37]:
arr[:, 0].reshape(3, 1)

array([[0],
       [3],
       [6]])

In [41]:
arr[[0, 2],:]

array([[0, 1, 2],
       [6, 7, 8]])

In [39]:
arr[[2,0]]

array([[6, 7, 8],
       [0, 1, 2]])

In [40]:
arr[:, [0, 2]]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [49]:
#마스킹
masking= arr < 5

In [43]:
arr[masking]

array([0, 1, 2, 3, 4])

In [44]:
arr[arr < 5]

array([0, 1, 2, 3, 4])

In [45]:
np.where(arr < 5, -1, 1)

array([[-1, -1, -1],
       [-1, -1,  1],
       [ 1,  1,  1]])

In [46]:
~(arr < 5)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [47]:
(arr > 2) & (arr < 7)

array([[False, False, False],
       [ True,  True,  True],
       [ True, False, False]])

In [48]:
(arr < 3) | (arr > 7)

array([[ True,  True,  True],
       [False, False, False],
       [False, False,  True]])

In [53]:
print(arr)
arr = np.maximum(arr, 5)
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[5, 5, 5],
       [5, 5, 5],
       [6, 7, 8]])

## np.ones, np.zeros

In [76]:
arr_0=np.ones((4, 5))
arr_0, arr_0.shape

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 (4, 5))

In [77]:
arr_0=np.ones((2, 3, 4))
arr_0, arr_0.shape

(array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]),
 (2, 3, 4))

In [78]:
np.zeros((2, 3, 8, 8))

array([[[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
       

## np.linspace

In [80]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [83]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## 난수 생성

In [59]:
import random

정수형 난수 생성
- np.random.randint(a, b) : a, b 사이의 균일분포의 정수 난수 1개 생성  
  
실수형 난수 생성
- np.random.normal: 정규분포에서 무작위 표본표출 (평균, 표준편차 이용)
- np.random.uniform: 균등분포에서 무작위 표본 표출 (최대, 최소값 이용)

In [63]:
random.randint(0, 10), random.randint(10, 20)

(6, 11)

In [61]:
[random.randint(0, 10) for _ in range(10)]

[6, 5, 7, 0, 0, 6, 8, 6, 8, 1]

In [62]:
np.random.randint(0, 11, size=10)

array([5, 7, 0, 0, 2, 4, 8, 3, 0, 3])

In [67]:
np.random.normal(0, 1, size=(3, 2)), np.random.normal(5, 1, size=(3, 2))

(array([[ 0.35872173,  0.93533534],
        [-0.23876416,  1.56661231],
        [ 0.05749646,  1.50392077]]),
 array([[5.14892087, 7.7373328 ],
        [5.91484023, 4.30583316],
        [4.10553371, 4.80601021]]))

In [68]:
np.random.uniform(0, 1, size=(3, 2)), np.random.uniform(5,1, size=(3, 2))

(array([[0.41863977, 0.65040499],
        [0.83790382, 0.65777471],
        [0.81250211, 0.84214996]]),
 array([[4.23274985, 4.68281082],
        [4.86971565, 4.20106455],
        [3.52032409, 3.59536168]]))

In [69]:
samples = np.arange(10)
samples

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.random.shuffle(samples)
samples

array([1, 4, 8, 2, 0, 7, 5, 9, 3, 6])

In [72]:
print(np.random.permutation(samples))
samples

[8 9 0 4 3 6 2 1 7 5]


array([1, 4, 8, 2, 0, 7, 5, 9, 3, 6])

np.random.suffle와 np.random.permutation은 매우 비슷하지만 suffle을 사용하면 기존 변수에 덮어써진다는 것을 기억하세요!

In [74]:
np.random.choice(samples, len(samples)), np.random.choice(samples, 3)

(array([7, 0, 7, 8, 9, 3, 6, 0, 0, 8]), array([4, 5, 6]))

In [54]:
arr = np.random.randn(3, 2)
arr

array([[ 0.13101439, -2.14097653],
       [ 0.21157055,  0.05758906],
       [-0.98680107,  0.22343504]])

In [56]:
arr.mean(), arr.mean(axis=0), arr.mean(axis=1), arr.shape

(-0.4173614258995832,
 array([-0.21473871, -0.61998414]),
 array([-1.00498107,  0.13457981, -0.38168301]),
 (3, 2))

In [57]:
arr = np.array([0, 1] * 3)
arr

array([0, 1, 0, 1, 0, 1])

In [58]:
np.unique(arr, return_counts=True)

(array([0, 1]), array([3, 3]))

## 기본 함수

In [91]:
x=np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [93]:
np.mean(x), np.mean(x, axis=0), np.mean(x, axis=1)

(7.0, array([5., 6., 7., 8., 9.]), array([ 2.,  7., 12.]))

In [94]:
x.mean()

7.0

In [96]:
np.max(x), np.max(x, axis=0), np.max(x, axis=1)

(14, array([10, 11, 12, 13, 14]), array([ 4,  9, 14]))

In [97]:
np.argmax(x), np.argmax(x, axis=0), np.argmax(x, axis=1)

(14, array([2, 2, 2, 2, 2]), array([4, 4, 4]))

In [98]:
np.var(x), np.median(x), np.std(x)

(18.666666666666668, 7.0, 4.320493798938574)

In [100]:
np.sum(x, axis=None), np.sum(x, axis=0), np.sum(x, axis=1)

(105, array([15, 18, 21, 24, 27]), array([10, 35, 60]))

In [101]:
np.cumsum(x)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105])

In [102]:
z = np.random.randn(10)
print(z)
np.where(z > 0, z, 0)

[ 3.55481217 -0.31169964  0.45607365 -0.1202055  -0.56894289 -0.60925265
 -1.88779268  0.45981036 -0.32704425 -1.58074946]


array([3.55481217, 0.        , 0.45607365, 0.        , 0.        ,
       0.        , 0.        , 0.45981036, 0.        , 0.        ])

## 브로드캐스팅

In [103]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)
x * y

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.13205888 0.96755013 0.01046564 0.33403973 0.13178533]
 [0.0307376  0.94029368 0.21224125 0.66707916 0.85806472]
 [0.80571151 0.10922704 0.26122405 0.78963793 0.85029828]]


array([[ 0.        ,  0.96755013,  0.02093127,  1.00211918,  0.52714131],
       [ 0.15368802,  5.64176207,  1.48568877,  5.3366333 ,  7.72258244],
       [ 8.05711506,  1.20149743,  3.13468862, 10.26529306, 11.90417585]])

In [104]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [ ]:
a = np.arange(12).reshape(4, 3)
b = np.arange(0, 3)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(d)