## __PyTorch Basic__ (@Yeji Choi)
### 2022.04.07


In [1]:
import numpy as np
import torch

### 배열 다루기  

- numpy 이용

In [2]:
arr_1=np.array([0,1,2,3,4,5,6,7,8,9])
arr_2=np.array(range(10))
arr_1, arr_2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [3]:
print('Rand of arr:', arr_1.ndim)
print('Shape of arr:', arr_1.shape)

Rand of arr: 1
Shape of arr: (10,)


In [4]:
print(arr_1[:5], arr_1[3], arr_1[-1], arr_1[-1:])

[0 1 2 3 4] 3 9 [9]


In [5]:
arr_3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_4=np.array([range(1,10)]).reshape(3,3)
arr_5=np.array([range(1,4),range(4,7),range(7,10)])

In [6]:
arr_3, arr_4, arr_5

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

- PyTorch 이용

In [7]:
t_arr=torch.FloatTensor([0,1,2,3,4,5,6])
print(t_arr)

tensor([0., 1., 2., 3., 4., 5., 6.])


- shape과 size

In [8]:
print(t_arr.dim())
print(t_arr.shape)
print(t_arr.size())
print(t_arr[:2],t_arr[-1], t_arr[1:6:2])

1
torch.Size([7])
torch.Size([7])
tensor([0., 1.]) tensor(6.) tensor([1., 3., 5.])


In [9]:
t_arr_2=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
print(t_arr_2)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [10]:
print(t_arr_2.dim())
print(t_arr_2.shape)
print(t_arr_2.size())
print(t_arr_2[:,1])
print(t_arr_2[:,1].size())
print(t_arr_2[:2,-1:])

2
torch.Size([3, 3])
torch.Size([3, 3])
tensor([2., 5., 8.])
torch.Size([3])
tensor([[3.],
        [6.]])


- 연산

In [11]:
t1 = torch.FloatTensor([3,3])
t2 = torch.FloatTensor([1,4])
print(t1+t2)

tensor([4., 7.])


In [12]:
t1 = torch.FloatTensor([3,3])
t2 = torch.FloatTensor([1])
print(t1+t2)

tensor([4., 4.])


In [13]:
t1 = torch.FloatTensor([[2,3]])
t2 = torch.FloatTensor([[1],[4]])
print(t1+t2)

tensor([[3., 4.],
        [6., 7.]])


### matmul (행렬의 곱셈)과 mul (원소별 곱셈)의 차이

In [14]:
t1 = torch.FloatTensor([[1,2],[3,4]])
t2 = torch.FloatTensor([[5],[6]])
print(t1)
print(t2)
print('Shape of Matrix t1: ', t1.shape)
print('Shape of Matrix t2: ', t2.shape)
print(t1.matmul(t2))
print(t1.matmul(t2).shape)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5.],
        [6.]])
Shape of Matrix t1:  torch.Size([2, 2])
Shape of Matrix t2:  torch.Size([2, 1])
tensor([[17.],
        [39.]])
torch.Size([2, 1])


In [16]:
t1 = torch.FloatTensor([[1,2],[3,4]])
t2 = torch.FloatTensor([[5],[6]])
print('Shape of Matrix t1: ', t1.shape)
print('Shape of Matrix t2: ', t2.shape)
print(t1)
print(t2)
print(t1*t2)
print(t1.mul(t2))
print(t1.mul(t2).shape)

Shape of Matrix t1:  torch.Size([2, 2])
Shape of Matrix t2:  torch.Size([2, 1])
tensor([[1., 2.],
        [3., 4.]])
tensor([[5.],
        [6.]])
tensor([[ 5., 10.],
        [18., 24.]])
tensor([[ 5., 10.],
        [18., 24.]])
torch.Size([2, 2])


 __'*'연산자를 이용한 broadcasting 가능__

- Max, Argmax

In [17]:
t1 = torch.FloatTensor([1,2,3,4])
print(t1.mean())

tensor(2.5000)


In [18]:
t1 = torch.FloatTensor([[1,2],[3,4]])
print(t1)
print(t1.mean())
print(t1.mean(dim=0))
print(t1.mean(dim=1))
print(t1.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [19]:
t1 = torch.FloatTensor([[1,2],[3,4]])
print(t1)
print(t1.sum())
print(t1.sum(dim=0))
print(t1.sum(dim=1))
print(t1.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [27]:
t1 = torch.FloatTensor([[1,2,5],[4,3,7]])
print(t1.shape)
print(t1,'\n')
print(t1.max(),'\n')
print(t1.max(dim=0),'\n')
print(t1.max(dim=1),'\n')
print(t1.max(dim=-1))

torch.Size([2, 3])
tensor([[1., 2., 5.],
        [4., 3., 7.]]) 

tensor(7.) 

torch.return_types.max(
values=tensor([4., 3., 7.]),
indices=tensor([1, 1, 1])) 

torch.return_types.max(
values=tensor([5., 7.]),
indices=tensor([2, 2])) 

torch.return_types.max(
values=tensor([5., 7.]),
indices=tensor([2, 2]))


In [28]:
print(t1.max(dim=0).values)
print(t1.max(dim=0).indices) # Argmax

tensor([4., 3., 7.])
tensor([1, 1, 1])


- 배열 확인 및 바꾸기 - view(reshape)

In [29]:
t=np.array([range(5),range(5,10),range(10,15)])
print(t)
print(t.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


In [30]:
ft=torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])
torch.Size([3, 5])


In [31]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
torch.Size([5, 3])


In [32]:
print(t.reshape(-1,3).astype('float'))

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]


In [33]:
print(ft.view([-1,1,3]))

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]],

        [[12., 13., 14.]]])


In [34]:
print(ft.view([-1,1,3]).shape)

torch.Size([5, 1, 3])


- 차원 줄이기, 늘리기

In [35]:
ft=torch.FloatTensor([[0],[1],[2]])
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [36]:
ft_sq=ft.squeeze()
print(ft_sq.unsqueeze(0))
print(ft_sq.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [37]:
ft_2=torch.FloatTensor([[[0],[1],[2]],[[3],[4],[5]]])
print(ft_2.shape)

torch.Size([2, 3, 1])


In [38]:
ft_sq=ft_2.squeeze()
ft_sq_sq=ft_sq.squeeze()
ft_sq.shape, ft_sq_sq.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [39]:
print(ft.shape)
ft_sq=ft.squeeze()
print(ft.squeeze().shape)
print(ft_sq.unsqueeze(0))
print(ft_sq.unsqueeze(0).shape)

torch.Size([3, 1])
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [40]:
print(ft.shape)
ft_sq=ft.squeeze()
print(ft_sq.unsqueeze(1))
print(ft_sq.unsqueeze(1).shape)

torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [41]:
print(ft.shape)
ft_sq=ft.squeeze()
print(ft_sq.unsqueeze(-1))
print(ft_sq.unsqueeze(-1).shape)

torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


- 차원 합치기

In [42]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=0).shape)
print(torch.cat([x,y], dim=1))
print(torch.cat([x,y], dim=1).shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
torch.Size([2, 4])


In [43]:
x=torch.FloatTensor([1,2])
y=torch.FloatTensor([3,4])
z=torch.FloatTensor([5,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


- 배열 요소형 변환

In [44]:
long_t=torch.LongTensor([1,2,3,4])
print(long_t)

tensor([1, 2, 3, 4])


In [45]:
print(long_t.float())

tensor([1., 2., 3., 4.])


In [46]:
byte_t=torch.ByteTensor([True, False, False, True])
print(byte_t)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [47]:
byte_t.float()

tensor([1., 0., 0., 1.])

- Ones and Zeros

In [48]:
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


- 메모리 사용 줄이기

In [49]:
x=torch.FloatTensor([[1,2],[3,4]])

In [50]:
print(x.mul(2))
print(x)
print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
